insert into student (name, address, gender, birthday) values ('Eartha Russi', '57 Gale Circle', 'Female', '10-01-2006');
insert into student (name, address, gender, birthday) values ('Korie Ambrosetti', '88540 Trailsway Pass', 'Female', '29-07-1988');
insert into student (name, address, gender, birthday) values ('Fancy Messum', '58 Scott Way', 'Female', '07-05-1981');
insert into student (name, address, gender, birthday) values ('Vito Manna', '5795 Brentwood Park', 'Male', '04-11-2009');
insert into student (name, address, gender, birthday) values ('Shaylynn Linklater', '9 Derek Court', 'Female', '30-11-2002');
insert into student (name, address, gender, birthday) values ('Wenonah Patemore', '41 Dennis Drive', 'Female', '02-01-2001');
insert into student (name, address, gender, birthday) values ('Larina Hyndley', '858 Grasskamp Junction', 'Female', '14-08-1990');
insert into student (name, address, gender, birthday) values ('Tansy Dalgarno', '5342 Donald Place', 'Female', '22-02-1982');
insert into student (name, address, gender, birthday) values ('Chris Rumford', '5 Clyde Gallagher Trail', 'Male', '22-03-2009');
insert into student (name, address, gender, birthday) values ('Tom Deighton', '628 Nelson Terrace', 'Male', '29-01-2005');
insert into student (name, address, gender, birthday) values ('Rayner Creigan', '4860 Marcy Terrace', 'Male', '12-06-1989');
insert into student (name, address, gender, birthday) values ('Leonard Sommerled', '27040 Granby Drive', 'Male', '26-09-1983');
insert into student (name, address, gender, birthday) values ('Reider Hartzog', '90250 Ridgeway Terrace', 'Male', '23-10-1992');
insert into student (name, address, gender, birthday) values ('Carl Scole', '2 Arkansas Trail', 'Male', '28-09-1997');
insert into student (name, address, gender, birthday) values ('Marja Gunda', '490 Dakota Trail', 'Female', '21-09-2005');
insert into student (name, address, gender, birthday) values ('Tarra Honniebal', '9552 Gerald Center', 'Female', '13-11-1975');
insert into student (name, address, gender, birthday) values ('Michelle Adnams', '0309 Fordem Way', 'Female', '03-11-2007');
insert into student (name, address, gender, birthday) values ('Isadore Epton', '84 Northfield Court', 'Male', '15-04-2002');
insert into student (name, address, gender, birthday) values ('Pearce Tetlow', '518 Morningstar Court', 'Male', '09-08-1996');
insert into student (name, address, gender, birthday) values ('Maxwell Kingham', '65472 Wayridge Drive', 'Male', '12-01-1988');
insert into student (name, address, gender, birthday) values ('Irvin Birt', '42 Prairie Rose Trail', 'Male', '11-04-2019');
insert into student (name, address, gender, birthday) values ('Zollie Lambrook', '043 Marquette Plaza', 'Male', '19-02-2000');
insert into student (name, address, gender, birthday) values ('Dane Keitch', '9139 Arapahoe Crossing', 'Male', '22-02-1976');
insert into student (name, address, gender, birthday) values ('Jedd Menier', '7637 Mccormick Parkway', 'Male', '21-08-1979');
insert into student (name, address, gender, birthday) values ('Nikolai Lodford', '3 Summerview Park', 'Male', '01-06-1981');
insert into student (name, address, gender, birthday) values ('Petronille Sleney', '2038 Waywood Place', 'Female', '21-03-1983');
insert into student (name, address, gender, birthday) values ('Gradeigh Harme', '375 Loomis Pass', 'Male', '21-07-1977');
insert into student (name, address, gender, birthday) values ('Alexandrina Gumley', '6900 Lake View Trail', 'Female', '18-07-2004');
insert into student (name, address, gender, birthday) values ('Carlyle Jedrzejewski', '0824 8th Center', 'Male', '04-12-2014');
insert into student (name, address, gender, birthday) values ('Binky Kinningley', '2216 Del Sol Place', 'Male', '16-12-2018');
insert into student (name, address, gender, birthday) values ('Felice Kohler', '2 Dwight Parkway', 'Female', '25-07-1999');
insert into student (name, address, gender, birthday) values ('Brigitta Skeffington', '06 Moose Alley', 'Female', '27-08-1999');
insert into student (name, address, gender, birthday) values ('Serge Gainsboro', '49 Mockingbird Center', 'Male', '29-01-1981');
insert into student (name, address, gender, birthday) values ('Ario Pharro', '31011 Colorado Trail', 'Male', '24-08-1989');
insert into student (name, address, gender, birthday) values ('Jessi Boriston', '507 Miller Hill', 'Female', '20-07-1991');
insert into student (name, address, gender, birthday) values ('Danyelle Mattussevich', '37 Crownhardt Lane', 'Female', '29-01-2014');
insert into student (name, address, gender, birthday) values ('Freemon Harder', '49 Bowman Crossing', 'Male', '08-06-1990');
insert into student (name, address, gender, birthday) values ('Sissie Larcher', '91885 Stoughton Center', 'Female', '24-11-2005');
insert into student (name, address, gender, birthday) values ('Toddie Gunner', '1147 Boyd Street', 'Male', '29-06-1978');
insert into student (name, address, gender, birthday) values ('Dara Grishanin', '296 Gulseth Road', 'Female', '07-03-1992');
insert into student (name, address, gender, birthday) values ('Charmian Vidloc', '96 Jana Point', 'Female', '17-07-2017');
insert into student (name, address, gender, birthday) values ('Giffy Hatley', '89 Ilene Pass', 'Male', '22-08-2008');
insert into student (name, address, gender, birthday) values ('Jannelle Morland', '2599 Scott Alley', 'Female', '11-09-2005');
insert into student (name, address, gender, birthday) values ('Hussein Howerd', '0 Killdeer Circle', 'Male', '02-10-2004');
insert into student (name, address, gender, birthday) values ('Laurence Goretti', '1107 Meadow Vale Park', 'Male', '28-11-1987');
insert into student (name, address, gender, birthday) values ('Giffy Jagiela', '1 Oak Valley Trail', 'Male', '11-11-1989');
insert into student (name, address, gender, birthday) values ('Ezmeralda Hards', '4775 Moose Center', 'Female', '09-12-1999');
insert into student (name, address, gender, birthday) values ('Octavius Waghorn', '003 Northwestern Road', 'Male', '07-08-2017');
insert into student (name, address, gender, birthday) values ('Dyanna Hallwood', '08973 Sugar Crossing', 'Female', '12-10-2005');
insert into student (name, address, gender, birthday) values ('Martyn Sydry', '13870 Maryland Road', 'Male', '08-05-2020');
insert into student (name, address, gender, birthday) values ('Nana Giovanizio', '4011 Pearson Parkway', 'Female', '12-11-2001');
insert into student (name, address, gender, birthday) values ('Gladi Houlahan', '3 Blackbird Way', 'Female', '11-11-2013');
insert into student (name, address, gender, birthday) values ('Rodrique Scalia', '6 Waubesa Place', 'Male', '26-10-2020');
insert into student (name, address, gender, birthday) values ('Geoff Itzkovich', '18297 Cardinal Alley', 'Male', '22-10-2005');
insert into student (name, address, gender, birthday) values ('Kalindi Pietasch', '062 Derek Hill', 'Female', '19-10-2000');
insert into student (name, address, gender, birthday) values ('Abby De Zuani', '6932 Warrior Way', 'Male', '29-08-1991');
insert into student (name, address, gender, birthday) values ('Roderic Coyett', '0272 Scoville Road', 'Male', '06-12-1989');
insert into student (name, address, gender, birthday) values ('Artemis Ashlee', '5 Evergreen Park', 'Male', '24-01-2020');
insert into student (name, address, gender, birthday) values ('Rozanna Dadley', '2963 Judy Trail', 'Female', '01-02-1979');
insert into student (name, address, gender, birthday) values ('Elijah Castagno', '229 Bluejay Street', 'Male', '24-10-1982');
insert into student (name, address, gender, birthday) values ('Idette Elsey', '43 Farmco Street', 'Female', '16-06-1978');
insert into student (name, address, gender, birthday) values ('Richard Kennerknecht', '8802 Duke Junction', 'Male', '20-06-1994');
insert into student (name, address, gender, birthday) values ('Charmain Stenet', '56204 Oriole Drive', 'Female', '01-10-1985');
insert into student (name, address, gender, birthday) values ('Andrei Folbig', '71422 Mallard Hill', 'Female', '27-04-2009');
insert into student (name, address, gender, birthday) values ('Viv Wigfall', '4 Eastlawn Place', 'Female', '03-09-1998');
insert into student (name, address, gender, birthday) values ('Farr Godsmark', '40 South Drive', 'Male', '25-07-2013');
insert into student (name, address, gender, birthday) values ('Malina Jennaway', '3622 Barnett Road', 'Female', '03-02-2006');
insert into student (name, address, gender, birthday) values ('Say McVee', '3013 Artisan Pass', 'Male', '14-08-1989');
insert into student (name, address, gender, birthday) values ('Emelyne Hounsom', '90244 Susan Plaza', 'Female', '12-01-2013');
insert into student (name, address, gender, birthday) values ('Solly Alty', '586 Waywood Alley', 'Male', '19-06-2000');
insert into student (name, address, gender, birthday) values ('Rusty Gresham', '9270 Old Gate Terrace', 'Male', '09-07-1995');
insert into student (name, address, gender, birthday) values ('Teddy Bortoloni', '683 Beilfuss Junction', 'Male', '05-02-1979');
insert into student (name, address, gender, birthday) values ('Had Gorler', '9 Bunker Hill Avenue', 'Male', '01-12-2009');
insert into student (name, address, gender, birthday) values ('Morty Searchwell', '42161 Green Ridge Lane', 'Male', '27-09-1993');
insert into student (name, address, gender, birthday) values ('Darice Yukhtin', '7 Moose Place', 'Female', '22-05-2018');
insert into student (name, address, gender, birthday) values ('Mordecai Kira', '031 Bultman Place', 'Male', '17-12-2013');
insert into student (name, address, gender, birthday) values ('Salli Surgen', '29 Debra Point', 'Female', '05-01-2014');
insert into student (name, address, gender, birthday) values ('Rosabelle Huc', '51180 Express Court', 'Female', '22-01-2001');
insert into student (name, address, gender, birthday) values ('Georgia Folli', '42502 Judy Pass', 'Female', '08-01-1977');
insert into student (name, address, gender, birthday) values ('Maribel Worcs', '8 Pine View Lane', 'Female', '24-11-1994');
insert into student (name, address, gender, birthday) values ('Petronia Crosston', '5 Atwood Crossing', 'Female', '21-03-1995');
insert into student (name, address, gender, birthday) values ('Zachariah Ronayne', '1852 Delladonna Lane', 'Male', '29-01-2021');
insert into student (name, address, gender, birthday) values ('Putnam Hunter', '7 Esker Lane', 'Male', '03-03-1993');
insert into student (name, address, gender, birthday) values ('Enid Tangye', '9002 Mandrake Alley', 'Female', '10-09-1991');
insert into student (name, address, gender, birthday) values ('Alan Loadwick', '5 Forster Circle', 'Male', '19-05-1991');
insert into student (name, address, gender, birthday) values ('Rachael Vallantine', '712 Jenifer Street', 'Female', '05-02-1987');
insert into student (name, address, gender, birthday) values ('Dorree Climar', '04857 Dottie Street', 'Female', '15-03-2020');
insert into student (name, address, gender, birthday) values ('Krishnah Divis', '94204 Northport Plaza', 'Male', '24-07-1986');
insert into student (name, address, gender, birthday) values ('Timofei Gerritsma', '46 Duke Crossing', 'Male', '22-04-2019');
insert into student (name, address, gender, birthday) values ('Paddie Osbaldstone', '6805 Ilene Terrace', 'Male', '25-07-1985');
insert into student (name, address, gender, birthday) values ('Gaston Challener', '57584 Columbus Road', 'Male', '04-03-1980');
insert into student (name, address, gender, birthday) values ('Siffre Goulston', '6 Farwell Trail', 'Male', '15-01-2012');
insert into student (name, address, gender, birthday) values ('Marcile Wasbey', '09619 Loftsgordon Junction', 'Female', '14-11-1989');
insert into student (name, address, gender, birthday) values ('Hillel Burnhill', '7 Farwell Road', 'Male', '13-01-1982');
insert into student (name, address, gender, birthday) values ('Berti Grinishin', '75191 Northfield Alley', 'Male', '16-01-1999');
insert into student (name, address, gender, birthday) values ('Katee Cusick', '01062 Barnett Plaza', 'Female', '28-06-2010');
insert into student (name, address, gender, birthday) values ('Valencia Keech', '3 Waywood Crossing', 'Female', '10-04-1997');
insert into student (name, address, gender, birthday) values ('Samara Brokenshire', '96 Springs Point', 'Female', '25-12-2004');
insert into student (name, address, gender, birthday) values ('Petra Durnian', '6 Fuller Alley', 'Female', '10-07-2013');
insert into student (name, address, gender, birthday) values ('Arly Hargey', '541 Moland Parkway', 'Female', '18-05-1980');
